import request from "supertest";
import pg from "pg";
import { randomUUID } from "node:crypto";
import { createRequire } from "node:module";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

const require = createRequire(import.meta.url); const { createApp } = require("../dist/backend/src/app.js"); const { env } = require("../dist/backend/src/config/env.js");
const pool = new pg.Pool({ connectionString: env.DATABASE_URL }); const app = createApp(); const suffix = `${Date.now()}-${Math.random().toString(16).slice(2)}`;
const workspaceA = randomUUID(), workspaceB = randomUUID(), planId = randomUUID(); let cookie, userId, otherId;
const headers = (workspaceId = workspaceA) => ({ Cookie: cookie, "X-Workspace-Id": workspaceId });
const teacher = (overrides = {}) => ({ teacherCode: `TCH-${suffix}-${randomUUID().slice(0, 5)}`, name: "Nadia Sultana", phone: "01712345678", defaultSalaryMinor: "2500000", ...overrides });
describe("teacher API", () => {
  beforeAll(async () => { const email=`teacher-${suffix}@example.test`; const signup=await request(app).post("/api/auth/sign-up/email").send({name:"Teacher Owner",email,password:"safe-test-password"}); userId=signup.body.user.id; const signin=await request(app).post("/api/auth/sign-in/email").send({email,password:"safe-test-password"}); cookie=signin.headers["set-cookie"]?.[0]; await pool.query("INSERT INTO plans (id,name,slug,duration_days,trial_days) VALUES ($1,$2,$3,30,0)",[planId,"Teacher Test",`teacher-${suffix}`]); await pool.query("INSERT INTO workspaces (id,name,slug,status) VALUES ($1,$2,$3,'active'),($4,$5,$6,'active')",[workspaceA,"Teacher A",`teacher-a-${suffix}`,workspaceB,"Teacher B",`teacher-b-${suffix}`]); await pool.query("INSERT INTO workspace_members (workspace_id,user_id,role_code) VALUES ($1,$2,101)",[workspaceA,userId]); await pool.query("INSERT INTO subscriptions (workspace_id,plan_id,status,expires_at) VALUES ($1,$2,'active',now()+interval '30 days')",[workspaceA,planId]); otherId=(await pool.query("INSERT INTO teachers (workspace_id,teacher_code,name) VALUES ($1,'OTHER','Other') RETURNING id",[workspaceB])).rows[0].id; });
  afterAll(async () => { await pool.query("DELETE FROM teachers WHERE workspace_id IN ($1,$2)",[workspaceA,workspaceB]); await pool.query("DELETE FROM subscriptions WHERE workspace_id=$1",[workspaceA]); await pool.query("DELETE FROM workspace_members WHERE workspace_id=$1",[workspaceA]); await pool.query("DELETE FROM workspaces WHERE id IN ($1,$2)",[workspaceA,workspaceB]); await pool.query("DELETE FROM plans WHERE id=$1",[planId]); await pool.query('DELETE FROM "user" WHERE id=$1',[userId]); await pool.end(); });
  it("creates, lists, updates, archives, and reactivates teachers", async () => { const created=await request(app).post("/api/v1/teachers").set(headers()).send(teacher({teacherCode:"T-1"})).expect(201); const id=created.body.data.id; await request(app).get("/api/v1/teachers?search=Nadia&status=active&page=1&limit=1").set(headers()).expect(200).expect(({body})=>expect(body.meta.total).toBe(1)); await request(app).patch(`/api/v1/teachers/${id}`).set(headers()).send({name:"Nadia Updated",status:"inactive"}).expect(200); await request(app).delete(`/api/v1/teachers/${id}`).set(headers()).expect(200).expect(({body})=>expect(body.data.status).toBe("archived")); await request(app).patch(`/api/v1/teachers/${id}`).set(headers()).send({status:"active"}).expect(200); });
  it("rejects duplicates, invalid input, and cross-workspace access", async () => { await request(app).post("/api/v1/teachers").set(headers()).send(teacher({teacherCode:"DUP"})).expect(201); await request(app).post("/api/v1/teachers").set(headers()).send(teacher({teacherCode:"DUP"})).expect(409); await request(app).post("/api/v1/teachers").set(headers()).send({teacherCode:"BAD",name:"Bad",phone:"123"}).expect(400); await request(app).get(`/api/v1/teachers/${otherId}`).set(headers()).expect(404); await request(app).get("/api/v1/teachers").set(headers(workspaceB)).expect(403); });
});
