import type { z } from "zod";
import type { enrollStudentSchema, updateEnrollmentSchema } from "../validation/batch-enrollment.validation";
import { and, asc, desc, eq } from "drizzle-orm";
import { withWorkspaceContext } from "../database/client";
import { batches, batchEnrollments } from "../database/schema/batches";
import { students } from "../database/schema/students";
import { AppError } from "../middleware/error-handler";
import { recordAuditLog } from "./audit-log.service";
type EnrollmentRow = Pick<typeof batchEnrollments.$inferSelect, "id" | "studentId" | "enrolledAt" | "status" | "feeOverrideMinor" | "discountMinor" | "createdAt" | "updatedAt"> & { studentCode: string; name: string; phone: string | null };
const map = (row: EnrollmentRow) => ({ id: row.id, studentId: row.studentId, studentCode: row.studentCode, name: row.name, phone: row.phone, joinedAt: row.enrolledAt, status: row.status, feeOverrideMinor: row.feeOverrideMinor?.toString() ?? null, discountMinor: row.discountMinor?.toString() ?? null, createdAt: row.createdAt, updatedAt: row.updatedAt });
async function batch(tx: Parameters<Parameters<typeof withWorkspaceContext>[1]>[0], workspaceId: string, batchId: string) { const [row] = await tx.select({ id: batches.id }).from(batches).where(and(eq(batches.id, batchId), eq(batches.workspaceId, workspaceId))).limit(1); if (!row) throw new AppError("BATCH_NOT_FOUND", "The batch was not found.", 404); }
export async function listBatchEnrollments(workspaceId: string, batchId: string) { return withWorkspaceContext(workspaceId, async (tx) => { await batch(tx, workspaceId, batchId); const rows = await tx.select({ id: batchEnrollments.id, studentId: students.id, studentCode: students.studentCode, name: students.fullName, phone: students.phone, enrolledAt: batchEnrollments.enrolledAt, status: batchEnrollments.status, feeOverrideMinor: batchEnrollments.feeOverrideMinor, discountMinor: batchEnrollments.discountMinor, createdAt: batchEnrollments.createdAt, updatedAt: batchEnrollments.updatedAt }).from(batchEnrollments).innerJoin(students, and(eq(students.id, batchEnrollments.studentId), eq(students.workspaceId, workspaceId))).where(and(eq(batchEnrollments.workspaceId, workspaceId), eq(batchEnrollments.batchId, batchId))).orderBy(desc(batchEnrollments.createdAt), asc(students.fullName)); return rows.map(map); }); }
export async function listStudentEnrollments(workspaceId: string, studentId: string) { return withWorkspaceContext(workspaceId, async (tx) => { const [student] = await tx.select({ id: students.id }).from(students).where(and(eq(students.id, studentId), eq(students.workspaceId, workspaceId))).limit(1); if (!student) throw new AppError("STUDENT_NOT_FOUND", "The student was not found.", 404); const rows = await tx.select({ id: batchEnrollments.id, batchId: batches.id, batchName: batches.name, joinedAt: batchEnrollments.enrolledAt, status: batchEnrollments.status, feeOverrideMinor: batchEnrollments.feeOverrideMinor, discountMinor: batchEnrollments.discountMinor }).from(batchEnrollments).innerJoin(batches, and(eq(batches.id, batchEnrollments.batchId), eq(batches.workspaceId, workspaceId))).where(and(eq(batchEnrollments.workspaceId, workspaceId), eq(batchEnrollments.studentId, studentId))).orderBy(desc(batchEnrollments.createdAt)); return rows.map((row) => ({ ...row, feeOverrideMinor: row.feeOverrideMinor?.toString() ?? null, discountMinor: row.discountMinor?.toString() ?? null })); }); }
export async function enrollStudent(workspaceId: string, actorUserId: string, batchId: string, input: z.infer<typeof enrollStudentSchema>) { try { await withWorkspaceContext(workspaceId, async (tx) => { await batch(tx, workspaceId, batchId); const [student] = await tx.select({ id: students.id }).from(students).where(and(eq(students.id, input.studentId), eq(students.workspaceId, workspaceId))).limit(1); if (!student) throw new AppError("STUDENT_NOT_FOUND", "The student was not found in this workspace.", 400); await tx.insert(batchEnrollments).values({ workspaceId, batchId, studentId: input.studentId, enrolledAt: input.joinedAt, feeOverrideMinor: input.feeOverrideMinor ?? null, discountMinor: input.discountMinor ?? null, createdBy: actorUserId }); await recordAuditLog(tx, { actorUserId, action: "batch.student_enrolled", entityType: "batch", entityId: batchId, workspaceId, metadata: { studentId: input.studentId } }); }); return listBatchEnrollments(workspaceId, batchId); } catch (error) { const databaseError = error && typeof error === "object" ? (error as { code?: string; cause?: { code?: string } }) : undefined; const code = databaseError?.code ?? databaseError?.cause?.code; if (code === "23505") throw new AppError("BATCH_STUDENT_ALREADY_ENROLLED", "This student is already actively enrolled in the batch.", 409); throw error; } }
export async function updateEnrollment(workspaceId: string, actorUserId: string, batchId: string, enrollmentId: string, input: z.infer<typeof updateEnrollmentSchema>) { await withWorkspaceContext(workspaceId, async (tx) => { await batch(tx, workspaceId, batchId); const { joinedAt, ...updates } = input; const [row] = await tx.update(batchEnrollments).set({ ...updates, ...(joinedAt === undefined ? {} : { enrolledAt: joinedAt }), updatedAt: new Date() }).where(and(eq(batchEnrollments.id, enrollmentId), eq(batchEnrollments.workspaceId, workspaceId), eq(batchEnrollments.batchId, batchId))).returning({ id: batchEnrollments.id }); if (!row) throw new AppError("ENROLLMENT_NOT_FOUND", "The enrollment was not found.", 404); await recordAuditLog(tx, { actorUserId, action: "batch.enrollment_updated", entityType: "batch", entityId: batchId, workspaceId, metadata: { enrollmentId } }); }); return listBatchEnrollments(workspaceId, batchId); }

export const archiveEnrollment = (
  workspaceId: string,
  actorUserId: string,
  batchId: string,
  enrollmentId: string,
) => updateEnrollment(workspaceId, actorUserId, batchId, enrollmentId, { status: "archived" });
