import { and, desc, eq, sql } from 'drizzle-orm';
import { db, withWorkspaceContext } from '../database/client';
import { smsCreditLedger, smsWallets } from '../database/schema/sms-wallet';
import { smsPackages, smsRechargeRequests } from '../database/schema/sms-packages';
import { workspaces } from '../database/schema/workspaces';
import { AppError } from '../middleware/error-handler';
import { recordAuditLog } from './audit-log.service';
export const listSmsPackages = (activeOnly = false) => db.select().from(smsPackages).where(activeOnly ? eq(smsPackages.isActive,true) : undefined).orderBy(smsPackages.credits);
export async function saveSmsPackage(id: string|undefined, input: {name:string;credits:bigint;priceMinor:bigint;isActive?:boolean}) { const values={...input, updatedAt:new Date()}; if(id){const [row]=await db.update(smsPackages).set(values).where(eq(smsPackages.id,id)).returning(); if(!row) throw new AppError('SMS_PACKAGE_NOT_FOUND','SMS package was not found.',404); return row;} const [row]=await db.insert(smsPackages).values({...input,isActive:input.isActive??true}).returning();return row; }
export async function submitSmsRecharge(workspaceId:string,userId:string,input:{packageId:string;paymentMethod:string;transactionId:string}) { return withWorkspaceContext(workspaceId,async tx=>{const [pkg]=await tx.select().from(smsPackages).where(and(eq(smsPackages.id,input.packageId),eq(smsPackages.isActive,true))).limit(1);if(!pkg)throw new AppError('SMS_PACKAGE_NOT_AVAILABLE','The selected SMS package is unavailable.',400);const [row]=await tx.insert(smsRechargeRequests).values({workspaceId,packageId:pkg.id,requestedByUserId:userId,credits:pkg.credits,amountMinor:pkg.priceMinor,paymentMethod:input.paymentMethod,transactionId:input.transactionId}).returning();await recordAuditLog(tx,{workspaceId,actorUserId:userId,action:'sms_recharge.submitted',entityType:'sms_recharge_request',entityId:row.id,metadata:{status:'pending'}});return row;});}
export async function listPendingSmsRecharges(){return db.select({request:smsRechargeRequests,workspace:{id:workspaces.id,name:workspaces.name},package:smsPackages}).from(smsRechargeRequests).innerJoin(workspaces,eq(workspaces.id,smsRechargeRequests.workspaceId)).innerJoin(smsPackages,eq(smsPackages.id,smsRechargeRequests.packageId)).where(eq(smsRechargeRequests.status,'pending')).orderBy(desc(smsRechargeRequests.createdAt));}
export async function reviewSmsRecharge(id:string,reviewer:string,status:'approved'|'rejected',reason?:string){return db.transaction(async tx=>{const [request]=await tx.select().from(smsRechargeRequests).where(eq(smsRechargeRequests.id,id)).for('update');if(!request||request.status!=='pending')throw new AppError('SMS_RECHARGE_ALREADY_REVIEWED','This SMS recharge request has already been reviewed or does not exist.',409);const now=new Date();if(status==='approved'){await tx.execute(sql`select set_config('app.workspace_id', ${request.workspaceId}, true)`);await tx.execute(sql`select set_config('app.sms_wallet_ledger_write', 'on', true)`);const [wallet]=await tx.update(smsWallets).set({availableCredits:sql`${smsWallets.availableCredits}+${request.credits}`,purchasedCredits:sql`${smsWallets.purchasedCredits}+${request.credits}`,updatedAt:now}).where(eq(smsWallets.workspaceId,request.workspaceId)).returning();if(!wallet)throw new AppError('SMS_WALLET_NOT_FOUND','SMS wallet was not found.',404);await tx.insert(smsCreditLedger).values({workspaceId:request.workspaceId,walletId:wallet.id,transactionType:'purchase',availableCreditsDelta:request.credits,reservedCreditsDelta:0n,availableCreditsAfter:wallet.availableCredits,reservedCreditsAfter:wallet.reservedCredits,referenceType:'sms_recharge_request',referenceId:request.id,actorUserId:reviewer});}const [row]=await tx.update(smsRechargeRequests).set({status,reviewedAt:now,reviewedByUserId:reviewer,rejectionReason:reason??null,updatedAt:now}).where(and(eq(smsRechargeRequests.id,id),eq(smsRechargeRequests.status,'pending'))).returning();await recordAuditLog(tx,{workspaceId:request.workspaceId,actorUserId:reviewer,action:`sms_recharge.${status}`,entityType:'sms_recharge_request',entityId:id,metadata:{status}});return row;});}
