import { and, count, desc, eq, ilike, or } from "drizzle-orm";
import { withWorkspaceContext } from "../database/client";
import { teachers } from "../database/schema/teachers";
import { AppError } from "../middleware/error-handler";
import type { z } from "zod";
import type { createTeacherSchema, listTeachersQuerySchema, updateTeacherSchema } from "../validation/teacher.validation";
type Create = z.infer<typeof createTeacherSchema>; type Update = z.infer<typeof updateTeacherSchema>; type List = z.infer<typeof listTeachersQuerySchema>;
const normalize = <T extends Record<string, unknown>>(value: T) => Object.fromEntries(Object.entries(value).map(([key, item]) => [key, item === "" ? null : item])) as T;
function conflict(error: unknown): never { const code = (error as { code?: string; cause?: { code?: string } })?.code ?? (error as { cause?: { code?: string } })?.cause?.code; if (code === "23505") throw new AppError("TEACHER_CODE_ALREADY_EXISTS", "A teacher with this code already exists in this workspace.", 409); throw error; }
function map(row: typeof teachers.$inferSelect) { return { ...row, defaultSalaryMinor: row.defaultSalaryMinor.toString() }; }
export async function createTeacher(workspaceId: string, input: Create) { try { return await withWorkspaceContext(workspaceId, async (tx) => map((await tx.insert(teachers).values({ workspaceId, ...normalize(input) }).returning())[0])); } catch (error) { return conflict(error); } }
export async function getTeacher(workspaceId: string, id: string) { return withWorkspaceContext(workspaceId, async (tx) => { const [row] = await tx.select().from(teachers).where(and(eq(teachers.id, id), eq(teachers.workspaceId, workspaceId))).limit(1); if (!row) throw new AppError("TEACHER_NOT_FOUND", "The teacher was not found.", 404); return map(row); }); }
export async function listTeachers(workspaceId: string, input: List) { return withWorkspaceContext(workspaceId, async (tx) => { const filters = [eq(teachers.workspaceId, workspaceId)]; if (input.status) filters.push(eq(teachers.status, input.status)); if (input.search) { const term = `%${input.search}%`; filters.push(or(ilike(teachers.name, term), ilike(teachers.teacherCode, term), ilike(teachers.phone, term), ilike(teachers.email, term), ilike(teachers.subjectSpecialty, term))!); } const where = and(...filters); const [rows, totals] = await Promise.all([tx.select().from(teachers).where(where).orderBy(desc(teachers.createdAt), desc(teachers.id)).limit(input.limit).offset((input.page - 1) * input.limit), tx.select({ total: count() }).from(teachers).where(where)]); const total = Number(totals[0]?.total ?? 0); return { data: rows.map(map), meta: { page: input.page, limit: input.limit, total, totalPages: Math.max(1, Math.ceil(total / input.limit)) } }; }); }
export async function updateTeacher(workspaceId: string, id: string, input: Update) { try { return await withWorkspaceContext(workspaceId, async (tx) => { const [row] = await tx.update(teachers).set({ ...normalize(input), updatedAt: new Date() }).where(and(eq(teachers.id, id), eq(teachers.workspaceId, workspaceId))).returning(); if (!row) throw new AppError("TEACHER_NOT_FOUND", "The teacher was not found.", 404); return map(row); }); } catch (error) { return conflict(error); } }
export const archiveTeacher = (workspaceId: string, id: string) => updateTeacher(workspaceId, id, { status: "archived" });
