import type { RequestHandler } from "express";
import { createAcademicReference, listAcademicReferences, renameAcademicReference, updateAcademicReferenceStatus } from "../services/academic-reference.service";
import { academicIdSchema, academicResourceSchema, createAcademicReferenceSchema, renameAcademicReferenceSchema, updateAcademicReferenceStatusSchema } from "../validation/academic.validation";

function invalid(res: Parameters<RequestHandler>[1]) { res.status(400).json({ error: { code: "VALIDATION_ERROR", message: "Request validation failed." } }); }
function resource(req: Parameters<RequestHandler>[0]) { return academicResourceSchema.safeParse(req.params.resource); }
export const listAcademicReferencesController: RequestHandler = async (req, res, next) => { const parsed = resource(req); if (!parsed.success) return invalid(res); try { res.json({ data: await listAcademicReferences(req.workspaceContext!.workspaceId, parsed.data) }); } catch (error) { next(error); } };
export const createAcademicReferenceController: RequestHandler = async (req, res, next) => { const key = resource(req); const input = createAcademicReferenceSchema.safeParse(req.body); if (!key.success || !input.success) return invalid(res); try { res.status(201).json({ data: await createAcademicReference(req.workspaceContext!.workspaceId, key.data, input.data) }); } catch (error) { next(error); } };
export const renameAcademicReferenceController: RequestHandler = async (req, res, next) => { const key = resource(req); const id = academicIdSchema.safeParse(req.params.id); const input = renameAcademicReferenceSchema.safeParse(req.body); if (!key.success || !id.success || !input.success) return invalid(res); try { res.json({ data: await renameAcademicReference(req.workspaceContext!.workspaceId, key.data, id.data, input.data) }); } catch (error) { next(error); } };
export const updateAcademicReferenceStatusController: RequestHandler = async (req, res, next) => { const key = resource(req); const id = academicIdSchema.safeParse(req.params.id); const input = updateAcademicReferenceStatusSchema.safeParse(req.body); if (!key.success || !id.success || !input.success) return invalid(res); try { res.json({ data: await updateAcademicReferenceStatus(req.workspaceContext!.workspaceId, key.data, id.data, input.data.isActive) }); } catch (error) { next(error); } };
