import type { RequestHandler } from "express";
import { assignBatchTeacher, listBatchTeachers, removeBatchTeacher, updateBatchTeacher } from "../services/batch-teacher.service";
import { assignBatchTeacherSchema, batchTeacherIdSchema, updateBatchTeacherSchema } from "../validation/batch-teacher.validation";

const invalid = (res: Parameters<RequestHandler>[1]) => res.status(400).json({ error: { code: "VALIDATION_ERROR", message: "Request validation failed." } });
export const listBatchTeachersController: RequestHandler = async (req, res, next) => { const params = batchTeacherIdSchema.pick({ batchId: true }).safeParse({ batchId: req.params.id }); if (!params.success) return invalid(res); try { res.json({ data: await listBatchTeachers(req.workspaceContext!.workspaceId, params.data.batchId) }); } catch (error) { next(error); } };
export const assignBatchTeacherController: RequestHandler = async (req, res, next) => { const params = batchTeacherIdSchema.pick({ batchId: true }).safeParse({ batchId: req.params.id }), input = assignBatchTeacherSchema.safeParse(req.body); if (!params.success || !input.success) return invalid(res); try { res.status(201).json({ data: await assignBatchTeacher(req.workspaceContext!.workspaceId, req.authenticatedUser!.id, params.data.batchId, input.data) }); } catch (error) { next(error); } };
export const updateBatchTeacherController: RequestHandler = async (req, res, next) => { const params = batchTeacherIdSchema.safeParse({ batchId: req.params.id, teacherId: req.params.teacherId }), input = updateBatchTeacherSchema.safeParse(req.body); if (!params.success || !input.success) return invalid(res); try { res.json({ data: await updateBatchTeacher(req.workspaceContext!.workspaceId, req.authenticatedUser!.id, params.data.batchId, params.data.teacherId, input.data.isPrimary) }); } catch (error) { next(error); } };
export const removeBatchTeacherController: RequestHandler = async (req, res, next) => { const params = batchTeacherIdSchema.safeParse({ batchId: req.params.id, teacherId: req.params.teacherId }); if (!params.success) return invalid(res); try { res.json({ data: await removeBatchTeacher(req.workspaceContext!.workspaceId, req.authenticatedUser!.id, params.data.batchId, params.data.teacherId) }); } catch (error) { next(error); } };
